version: '3'

services:
  lora_data_fetcher:
    container_name: lora_data_fetcher
    build:
      context: ./
      dockerfile: Dockerfile_armv7l
    volumes:
      - "/dev/shm/receive_fifo:/dev/shm/receive_fifo"
    restart: always

  influxdb:
    container_name: influxdb
    image: influxdb:1.7.5
    ports:
      - '8086:8086'
    volumes:
      - $VOLUME_DIR/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB
      - INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
    restart: always

  chronograf:
    container_name: chronograf
    image: arm32v7/chronograf:1.7.8
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - $VOLUME_DIR/chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:6.1.4
    ports:
      - '3000:3000'
    volumes:
      - $VOLUME_DIR/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
    restart: always
